# SQlite
jakarta.persistence.jdbc.url=jdbc:sqlite:C:/Users/40741/IdeaProjects/animale_11.06.2025/JocAnimaleMPP.db
hibernate.connection.url=jdbc:sqlite:C:/Users/40741/IdeaProjects/animale_11.06.2025/JocAnimaleMPP.db
# Credentials
#jakarta.persistence.jdbc.user=
#jakarta.persistence.jdbc.password=

#create/none/update
jakarta.persistence.schema-generation.database.action=update

# SQL statement logging
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

